---
apiVersion: v2
name: nginx-plus-ingress
type: application
version: 0.16.2
appVersion: 3.0.2
dependencies:
  - name: nginx-ingress
    version: 0.16.2
    repository: https://helm.nginx.com/stable
