---
nginx-ingress:
  controller:
    appprotect:
      enable: true
    appprotectdos:
      enable: true
    enableSnippets: true
    image:
      repository: private-registry.nginx.com/nginx-ic-nap-dos/nginx-plus-ingress
      tag: 3.0.2
    nginxplus: true
    nginxStatus:
      allowCidrs: 0.0.0.0/0
      port: 9000
    readyStatus:
      initialDelaySeconds: 30
    serviceAccount:
      imagePullSecretName: regcred
    service:
      customPorts:
        - port: 9114
          targetPort: service-insight
          nodePort: 31000
          protocol: TCP
          name: service-insight
        - port: 9000
          targetPort: 9000
          nodePort: 32000
          protocol: TCP
          name: nginx-status
  prometheus:
    create: true
  serviceInsight:
    create: true
